spring.application.name=api-produto

# Porta em que a aplicação será iniciada
server.port=8080

# Define qual perfil de configuração será carregado junto com este arquivo.
# 'local' carrega o arquivo application-local.properties com as credenciais do ambiente de desenvolvimento.
# Em produção, substitua por 'prod' e crie o arquivo application-prod.properties correspondente.
spring.profiles.active=local

# Driver JDBC do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Estratégia de geração do schema do banco de dados pelo Hibernate.
# 'update': atualiza o schema automaticamente com base nas entidades, sem apagar dados existentes.
spring.jpa.hibernate.ddl-auto=update